SET SESSION sql_mode = REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY', '');

DROP TEMPORARY TABLE IF EXISTS stg_myrep_cutoff_import_full;
CREATE TEMPORARY TABLE stg_myrep_cutoff_import_full (
  cutoff_group varchar(50) DEFAULT NULL,
  cluster_name varchar(255) DEFAULT NULL,
  cluster_code varchar(100) DEFAULT NULL,
  regional_name varchar(100) DEFAULT NULL,
  province_name varchar(100) DEFAULT NULL,
  city_name varchar(100) DEFAULT NULL,
  team_name varchar(100) DEFAULT NULL,
  rpm varchar(100) DEFAULT NULL,
  sm varchar(100) DEFAULT NULL,
  spv varchar(100) DEFAULT NULL,
  status_current varchar(50) DEFAULT NULL,
  status_bak varchar(50) DEFAULT NULL,
  status_valsal varchar(50) DEFAULT NULL,
  status_batch_approval varchar(50) DEFAULT NULL,
  status_drm varchar(50) DEFAULT NULL,
  status_atp varchar(50) DEFAULT NULL,
  status_checklist_document varchar(50) DEFAULT NULL,
  hp_plan varchar(50) DEFAULT NULL,
  homepass_bak varchar(50) DEFAULT NULL,
  homepass_valsal varchar(50) DEFAULT NULL,
  hp_donasi varchar(50) DEFAULT NULL,
  homepass_drm varchar(50) DEFAULT NULL,
  olt_name varchar(255) DEFAULT NULL,
  ba_open_date varchar(50) DEFAULT NULL,
  bak_date varchar(50) DEFAULT NULL,
  valsal_date varchar(50) DEFAULT NULL,
  submission_date varchar(50) DEFAULT NULL,
  released_at varchar(50) DEFAULT NULL,
  drm_date varchar(50) DEFAULT NULL,
  email_atp_date varchar(50) DEFAULT NULL,
  actual_atp_date varchar(50) DEFAULT NULL,
  rfs_cluster_id varchar(50) DEFAULT NULL,
  remark_general text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
INSERT INTO stg_myrep_cutoff_import_full ($(cutoff_group cluster_name cluster_code regional_name province_name city_name team_name rpm sm spv status_current status_bak status_valsal status_batch_approval status_drm status_atp status_checklist_document hp_plan homepass_bak homepass_valsal hp_donasi homepass_drm olt_name ba_open_date bak_date valsal_date submission_date released_at drm_date email_atp_date actual_atp_date rfs_cluster_id remark_general -join ',')) VALUES
('ATP','KELURAHAN DENGKEK PATI','PTI000198','REGIONAL 3','JATENG','PATI',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'591',NULL,NULL,NULL,NULL,NULL,NULL,'2025-02-12','2026-07-02','2026-10-02',NULL,NULL),
('ATP','KELURAHAN COT CUT ACEH','BNA000326','REGIONAL 1','NAD','ACEH',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'432',NULL,NULL,NULL,NULL,NULL,NULL,'2025-10-31',NULL,'2026-02-27',NULL,NULL),
('ATP','PERUMAHAN JEULINGKE RESIDENCE','BNA000129','REGIONAL 1','NAD','ACEH',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'500',NULL,NULL,NULL,NULL,NULL,NULL,'2025-10-14',NULL,'2026-02-27',NULL,NULL),
('RFS','TUNGGULPANDEAN RW 01 JEPARA','JPA000331','REGIONAL 3','JATENG','JEPARA',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'329',NULL,NULL,NULL,NULL,NULL,NULL,'2025-02-13',NULL,NULL,NULL,NULL),
('RFS','TUNGGULPANDEAN RW 02 JEPARA','JPA000332','REGIONAL 3','JATENG','JEPARA',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'323',NULL,NULL,NULL,NULL,NULL,NULL,'2025-02-13',NULL,NULL,NULL,NULL),
('RFS','Perumahan Mapanget Griya 4 Minahasa','MND000086','REGIONAL 5','SULUT','MANADO',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'282',NULL,NULL,NULL,NULL,NULL,NULL,'2025-07-05','2026-04-23','2026-04-23',NULL,NULL),
('RFS','PERUMAHAN GRIYA PANIKI INDAH LINGKUNGAN 10 PANIKI BAWAH MANADO','MND000267','REGIONAL 5','SULUT','MANADO',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'2205',NULL,NULL,NULL,NULL,NULL,NULL,'2025-08-12',NULL,NULL,NULL,NULL),
('RFS','PERUMAHAN GRIYA PANIKI INDAH LINGKUNGAN 5 BENGKOL MANADO','MND000268','REGIONAL 5','SULUT','MANADO',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'2647',NULL,NULL,NULL,NULL,NULL,NULL,'2025-09-06',NULL,NULL,NULL,NULL),
('RFS','PERUMAHAN GRIYA PANIKI INDAH LINGKUNGAN 9 DAN 10 BUHA MANADO','MND000269','REGIONAL 5','SULUT','MANADO',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'1989',NULL,NULL,NULL,NULL,NULL,NULL,'2025-08-16',NULL,NULL,NULL,NULL),
('ATP','LEMAHDUWUR RW 02 ADIWERNA','TGL000637','REGIONAL 3','JATENG','TEGAL',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'134',NULL,NULL,NULL,NULL,NULL,NULL,'2025-11-05',NULL,'2026-04-01',NULL,NULL),
('ATP','SUREN RW 03 PURWOREJO',NULL,'REGIONAL 3','JATENG','PURWOREJO',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'331',NULL,NULL,NULL,NULL,NULL,NULL,'2025-11-07',NULL,'2026-02-09',NULL,NULL),
('RFS','PONOROGO RT 01 SAMPAI 07 LUBUKLINGGAU','LLG000091','REGIONAL 1','SUMSEL','LUBUKLINGGAU',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'1147',NULL,NULL,NULL,NULL,NULL,NULL,'2025-07-25',NULL,NULL,NULL,NULL),
('ATP','RUKO JBD JAKARTA GARDEN CITY JAKARTA TIMUR','JKT006456','REGIONAL 2','JAKARTA','JAKARTA TIMUR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'137',NULL,NULL,NULL,NULL,NULL,NULL,'2025-07-26',NULL,NULL,NULL,NULL),
('ATP','OPEN AREA JALAN SAGATANI SINGKAWANG',NULL,'REGIONAL 4','KALBAR','SINGKAWANG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'178',NULL,NULL,NULL,NULL,NULL,NULL,'2025-11-05',NULL,'2026-02-27',NULL,NULL),
('RFS','Open Area Jl Kerjokra Bendungan','SGN000491','REGIONAL 3','JATENG','SRAGEN',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'624',NULL,NULL,NULL,NULL,NULL,NULL,'2025-07-28',NULL,NULL,NULL,NULL),
('RFS','PAL IX RW 10 PONTIANAK PONTIANAK','PTK000345','REGIONAL 4','KALBAR','PONTIANAK',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'348',NULL,NULL,NULL,NULL,NULL,NULL,'2025-09-11',NULL,NULL,NULL,NULL),
('RFS','OPEN AREA JALAN AHMAD YANI SINGKAWANG','SKW000041','REGIONAL 4','KALBAR','SINGKAWANG',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('ATP','KELURAHAN PAPPA MAKASSAR',NULL,'REGIONAL 5','SULSEL','MAKASSAR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'843',NULL,NULL,NULL,NULL,NULL,NULL,'2025-10-16','2026-04-25','2026-04-25',NULL,NULL),
('ATP','KELURAHAN PATANI MAKASSAR',NULL,'REGIONAL 5','SULSEL','MAKASSAR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'452',NULL,NULL,NULL,NULL,NULL,NULL,'2025-11-18','2026-04-08','2026-04-09',NULL,NULL),
('RFS','KOMPLEK PERUMAHAN DEPARTEMEN PERHUBUNGAN','JKT004351','REGIONAL 2','JAKARTA','JAKARTA TIMUR',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'226',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-17',NULL,NULL,NULL,NULL),
('RFS','OPEN AREA JALAN PERTANIAN SINGKAWANG','SKW000043','REGIONAL 4','KALBAR','SINGKAWANG',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'361',NULL,NULL,NULL,NULL,NULL,NULL,'2025-12-24',NULL,NULL,NULL,NULL),
('RFS','DUSUN GABUNGAN PAYA BUJOK SEULEUMAK LANGSA','LGS000032','REGIONAL 1','NAD','LANGSA',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'240',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-12',NULL,NULL,NULL,NULL),
('ATP','SIDAHARJA RW 10 SURADADI','TGL000930','REGIONAL 3','JATENG','TEGAL',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','DONE',NULL,NULL,NULL,NULL,'132',NULL,NULL,NULL,NULL,NULL,NULL,'2025-12-30',NULL,'2026-01-20',NULL,NULL),
('ATP','OPEN AREA JALAN PIOLA ISA BOLIHUANGGA GORONTALO','GTO000115','REGIONAL 5','GORONTALO','GORONTALO',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','PUNCLIST','NOT STARTED',NULL,NULL,NULL,NULL,'365',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-08','2026-04-23','2026-04-23',NULL,NULL),
('ATP','Satreyan RW 08 Kanigoro','BLT000234','REGIONAL 3','JATIM','BLITAR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','DONE',NULL,NULL,NULL,NULL,'180',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-08',NULL,'2026-02-17',NULL,NULL),
('ATP','KELURAHAN PADANG REJO LAMPUNG','BDL001436','REGIONAL 1','LAMPUNG','LAMPUNG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-03',NULL,NULL),
('ATP','DUSUN PAGELARAN LAMPUNG','BDL001437','REGIONAL 1','LAMPUNG','LAMPUNG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-03',NULL,NULL),
('ATP','Bendungan RW 03 Kedawung',NULL,'REGIONAL 3','JATENG','SRAGEN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'260',NULL,NULL,NULL,NULL,NULL,NULL,'2025-07-17',NULL,'2026-03-09',NULL,NULL),
('ATP','MONENG SEPATI RT 02 DAN 03 LUBUKLINGGAU','LLG000036','REGIONAL 1','SUMSEL','LUBUKLINGGAU',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','PUNCLIST','NOT STARTED',NULL,NULL,NULL,NULL,'202',NULL,NULL,NULL,NULL,NULL,NULL,'2025-12-22','2026-01-10','2026-01-10',NULL,NULL),
('ATP','BANJARAGUNG RW 01 TEGAL','TGL001373','REGIONAL 3','JATENG','TEGAL',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-01',NULL,NULL),
('ATP','SUNGAI RENGAS RW 06 PONTIANAK','PTK000347','REGIONAL 4','KALBAR','PONTIANAK',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'1811',NULL,NULL,NULL,NULL,NULL,NULL,'2025-10-15',NULL,NULL,NULL,NULL),
('ATP','TAMALLAYANG RW 01 SAMPAI 03 MAKASSAR','MKS001573','REGIONAL 5','SULSEL','MAKASSAR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'1302',NULL,NULL,NULL,NULL,NULL,NULL,'2025-10-10',NULL,'2026-04-09',NULL,NULL),
('RFS','PERUMAHAN BUHA GRIYA PERMAI MANADO','MND000055','REGIONAL 5','SULUT','MANADO',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'617',NULL,NULL,NULL,NULL,NULL,NULL,'2025-10-08',NULL,NULL,NULL,NULL),
('ATP','KELURAHAN TIBANG BANDA ACEH','4000075467','REGIONAL 1','NAD','ACEH',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'852',NULL,NULL,NULL,NULL,NULL,NULL,'2025-11-19','2026-01-28','2026-01-28',NULL,NULL),
('ATP','JATI RT 05 SAMPAI 12 RW 07','JKT006764','REGIONAL 2','JAKARTA','JAKARTA TIMUR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','PUNCLIST','NOT STARTED',NULL,NULL,NULL,NULL,'337',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-17',NULL,'2026-03-02',NULL,NULL),
('ATP','JATI RT 01 SAMPAI 03 RW 07','JKT006765','REGIONAL 2','JAKARTA','JAKARTA TIMUR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','PUNCLIST','NOT STARTED',NULL,NULL,NULL,NULL,'193',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-17',NULL,'2026-03-04',NULL,NULL),
('ATP','DESA PENDOWO BODEH','PML000585','REGIONAL 3','JATENG','PEMALANG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'650',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-09',NULL,'2026-02-28',NULL,NULL),
('ATP','KARANGTALOK RW 01 SAMPAI RW 06 PEMALANG','PML000537','REGIONAL 3','JATENG','PEMALANG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'614',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-13',NULL,'2026-02-28',NULL,NULL),
('ATP','MENTOR RW 01 PROBOLINGGO','PBL000302','REGIONAL 3','JATIM','PROBOLINGGO',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'267',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-14','2026-03-07','2026-03-09',NULL,NULL),
('ATP','MENTOR RW 02 PROBOLINGGO','PBL000303','REGIONAL 3','JATIM','PROBOLINGGO',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'219',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-14','2026-03-07','2026-03-09',NULL,NULL),
('ATP','MENTOR RW 03 PROBOLINGGO','PBL000304','REGIONAL 3','JATIM','PROBOLINGGO',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'143',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-14','2026-03-07','2026-03-09',NULL,NULL),
('ATP','MENTOR RW 04 PROBOLINGGO','PBL000305','REGIONAL 3','JATIM','PROBOLINGGO',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'170',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-14','2026-03-07','2026-03-09',NULL,NULL),
('ATP','KELURAHAN SEURIGET LANGSA','LGS000035','REGIONAL 1','NAD','LANGSA',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'828',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-22','2026-02-27','2026-02-27',NULL,NULL),
('RFS','DUSUN KAMPUNG KRAMAT SIMPANG EMPAT LHOKSEUMAWE','LSM000018','REGIONAL 1','NAD','LHOKSEUMAWE',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'882',NULL,NULL,NULL,NULL,NULL,NULL,'2025-09-26',NULL,NULL,NULL,NULL),
('ATP','DUSUN RAWA SAKTI KEUDE ACEH LHOKSEUMAWE','LSM000019','REGIONAL 1','NAD','LHOKSEUMAWE',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'185',NULL,NULL,NULL,NULL,NULL,NULL,'2025-09-26',NULL,NULL,NULL,NULL),
('ATP','OPEN AREA JALAN RAJA BILATULO HUTUO GORONTALO','GTO000116','REGIONAL 5','GORONTALO','GORONTALO',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'274',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-08','2026-03-12','2026-03-12',NULL,NULL),
('ATP','Desa Wailan Tomohon Utara','MND000344','REGIONAL 5','SULUT','MANADO',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'544',NULL,NULL,NULL,NULL,NULL,NULL,'2025-11-20',NULL,'2026-03-09',NULL,NULL),
('ATP','Pamengger RW 02 Jatibarang','BBS000301','REGIONAL 3','JATENG','BREBES',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','DONE',NULL,NULL,NULL,NULL,'411',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-13',NULL,'2026-02-13',NULL,NULL),
('ATP','SUREN RW 05 DAN RW 06 PURWOREJO','PWR000203','REGIONAL 3','JATENG','PURWOREJO',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'259',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-10',NULL,'2026-03-01',NULL,NULL),
('ATP','SUREN RW 01 DAN RW 02 PURWOREJO','PWR000148','REGIONAL 3','JATENG','PURWOREJO',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'187',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-10',NULL,'2026-03-01',NULL,NULL),
('ATP','Satreyan RW 04 Kanigoro','BLT000232','REGIONAL 3','JATIM','BLITAR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'521',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-20',NULL,'2026-04-24',NULL,NULL),
('ATP','Satreyan RW 09 Kanigoro','BLT000235','REGIONAL 3','JATIM','BLITAR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'188',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-08',NULL,'2026-02-18',NULL,NULL),
('ATP','Lingkungan 3 Tanjungsari','BDL000693','REGIONAL 1','LAMPUNG','LAMPUNG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'257',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-11',NULL,'2026-03-27',NULL,NULL),
('ATP','Lingkungan 4 Tanjungsari','BDL000693','REGIONAL 1','LAMPUNG','LAMPUNG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'173',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-11',NULL,'2026-03-27',NULL,NULL),
('RFS','TUNGGULPANDEAN RW 03 JEPARA','JPA000323','REGIONAL 3','JATENG','JEPARA',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'439',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-06',NULL,NULL,NULL,NULL),
('ATP','TLEKUNG RW 06 MALANG','MLG000310','REGIONAL 3','JATIM','MALANG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'177',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-12',NULL,'2026-04-29',NULL,NULL),
('ATP','KELURAHAN KARANG ANYAR LANGSA','LGS000026','REGIONAL 1','NAD','LANGSA',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'976',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-12','2026-04-24','2026-04-24',NULL,NULL),
('ATP','SATREYAN RW 07 BLITAR','BLT000389','REGIONAL 3','JATIM','BLITAR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'223',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-29',NULL,'2026-04-27',NULL,NULL),
('ATP','KELURAHAN LAM REH ACEH','BNA000244','REGIONAL 1','NAD','ACEH',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'198',NULL,NULL,NULL,NULL,NULL,NULL,'2025-09-10','2026-01-31','2026-01-31',NULL,NULL),
('RFS','UTERAN RW 03 GEGERTAN',NULL,'REGIONAL 3','JATIM','MADIUN',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('ATP','Kroyo RW 11 Karangmalang',NULL,'REGIONAL 3','JATENG','SRAGEN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'79',NULL,NULL,NULL,NULL,NULL,NULL,'2025-05-23',NULL,'2026-03-01',NULL,NULL),
('ATP','Plumbungan RW 06 Karangmalang',NULL,'REGIONAL 3','JATENG','SRAGEN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'356',NULL,NULL,NULL,NULL,NULL,NULL,'2025-06-14',NULL,'2026-03-09',NULL,NULL),
('ATP','Sine Dusun Ngablak Sragen',NULL,'REGIONAL 3','JATENG','SRAGEN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'100',NULL,NULL,NULL,NULL,NULL,NULL,'2025-06-10',NULL,'2026-03-09',NULL,NULL),
('ATP','MEGER RW 03 KLATEN','KLN001355','REGIONAL 3','JATENG','KLATEN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'245',NULL,NULL,NULL,NULL,NULL,NULL,'2025-04-23',NULL,'2026-03-09',NULL,NULL),
('ATP','MEGER RW 05 KLATEN','KLN001356','REGIONAL 3','JATENG','KLATEN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'172',NULL,NULL,NULL,NULL,NULL,NULL,'2025-04-23',NULL,'2026-03-09',NULL,NULL),
('ATP','Rengaspendawa RW 06 Larangan','BBS000348','REGIONAL 3','JATENG','BREBES',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'437',NULL,NULL,NULL,NULL,NULL,NULL,'2025-10-25',NULL,'2026-02-13',NULL,NULL),
('ATP','RANDUPUTIH RW 01 DAN 02 PROBOLINGGO','PBL000287','REGIONAL 3','JATIM','PROBOLINGGO',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'411',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-12','2026-04-16','2026-04-16',NULL,NULL),
('ATP','PERUMAHAN AMUNTAI','JMB000041','REGIONAL 1','JAMBI','JAMBI',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'441',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-12','2026-04-17','2026-04-18',NULL,NULL),
('ATP','KELURAHAN TANJUNG PINANG PALANGKARAYA','PLK000146','REGIONAL 4','KALTENG','PALANGKARAYA',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'1588',NULL,NULL,NULL,NULL,NULL,NULL,'2025-10-10',NULL,'2026-02-23',NULL,NULL),
('ATP','Perum Samarinda City',NULL,'REGIONAL 4','KALTIM','SAMARINDA',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','DONE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-02',NULL,NULL),
('ATP','SAMBOJA KUALA RT 03, 04, 15, DAN 16 KUTAI KARTANEGARA','4000090080','REGIONAL 4','KALTIM','BALIKPAPAN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'533',NULL,NULL,NULL,NULL,NULL,NULL,'2025-11-14',NULL,'2026-02-27',NULL,NULL),
('RFS','KELURAHAN BIREM PUNTONG LANGSA','LGS000027','REGIONAL 1','NAD','LANGSA',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'984',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-16',NULL,NULL,NULL,NULL),
('ATP','PERUMAHAN GREEN PURNAMA JAMBI','JMB001224','REGIONAL 1','JAMBI','JAMBI',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'145',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-16','2026-04-17','2026-04-18',NULL,NULL),
('ATP','PERUMAHAN GRAHA TENGGELA INDAH DSK GORONTALO','GTO000095','REGIONAL 5','GORONTALO','GORONTALO',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-12','2026-03-12',NULL,NULL),
('ATP','KELURAHAN SEMLARAN BOJONEGORO','BJN000391','REGIONAL 3','JATIM','BOJONEGORO',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'261',NULL,NULL,NULL,NULL,NULL,NULL,'2025-12-12','2026-01-28','2026-03-08',NULL,NULL),
('ATP','Open Area Jl Banua Anyar Banjarmasin Timur','BJM000833','REGIONAL 4','KALSEL','BANJARMASIN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'300',NULL,NULL,NULL,NULL,NULL,NULL,'2025-12-18','2026-01-26','2026-01-23',NULL,NULL),
('ATP','PERUMAHAN PESONA AKBAR ASRI 6 JAMBI','JMB001170','REGIONAL 1','JAMBI','JAMBI',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'60',NULL,NULL,NULL,NULL,NULL,NULL,'2025-12-22',NULL,'2026-02-24',NULL,NULL),
('ATP','PERUMAHAN PERMATA LAND BLOK ONIX JAMBI','JMB001166','REGIONAL 1','JAMBI','JAMBI',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'332',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-09',NULL,'2026-02-22',NULL,NULL),
('ATP','PERUMAHAN DIAMOND LAND DSK JAMBI','JMB001167','REGIONAL 1','JAMBI','JAMBI',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'101',NULL,NULL,NULL,NULL,NULL,NULL,'2025-12-22',NULL,'2026-02-22',NULL,NULL),
('ATP','BAGAN PETE RT 65 JAMBI','JMB000829','REGIONAL 1','JAMBI','JAMBI',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'140',NULL,NULL,NULL,NULL,NULL,NULL,'2025-12-23','2026-02-02','2026-02-22',NULL,NULL),
('ATP','PAGUMENGAN MAS RW 07 PEKALONGAN','PKL000739','REGIONAL 3','JATENG','PEKALONGAN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','DONE',NULL,NULL,NULL,NULL,'100',NULL,NULL,NULL,NULL,NULL,NULL,'2025-12-24',NULL,'2026-02-04',NULL,NULL),
('ATP','KLAREYAN RW 03 PETARUKAN','PML000457','REGIONAL 3','JATENG','PEMALANG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','DONE',NULL,NULL,NULL,NULL,'442',NULL,NULL,NULL,NULL,NULL,NULL,'2025-12-08',NULL,'2026-01-31',NULL,NULL),
('ATP','KLAREYAN RW 01 PETARUKAN','PML000529','REGIONAL 3','JATENG','PEMALANG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','DONE',NULL,NULL,NULL,NULL,'532',NULL,NULL,NULL,NULL,NULL,NULL,'2025-12-08',NULL,'2026-01-31',NULL,NULL),
('ATP','KLAREYAN RW 02 PETARUKAN','PML000532','REGIONAL 3','JATENG','PEMALANG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','DONE',NULL,NULL,NULL,NULL,'614',NULL,NULL,NULL,NULL,NULL,NULL,'2025-12-08',NULL,'2026-01-31',NULL,NULL),
('ATP','KLAREYAN RW 04 PETARUKAN','PML000533','REGIONAL 3','JATENG','PEMALANG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','DONE',NULL,NULL,NULL,NULL,'351',NULL,NULL,NULL,NULL,NULL,NULL,'2025-12-08',NULL,'2026-01-31',NULL,NULL),
('ATP','SABARU RW 01 PALANGKARAYA','PLK000133','REGIONAL 4','KALTENG','PALANGKARAYA',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'858',NULL,NULL,NULL,NULL,NULL,NULL,'2025-11-04',NULL,'2026-01-02',NULL,NULL),
('ATP','OPEN AREA JL HIDAYATUSSHIBYAN KALIMATI','TGL000399','REGIONAL 3','JATENG','TEGAL',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'240',NULL,NULL,NULL,NULL,NULL,NULL,'2025-12-31',NULL,'2026-02-12',NULL,NULL),
('ATP','DESA BANJARTURI TEGAL','TGL001302','REGIONAL 3','JATENG','TEGAL',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','DONE',NULL,NULL,NULL,NULL,'734',NULL,NULL,NULL,NULL,NULL,NULL,'2025-12-12',NULL,'2026-02-13',NULL,NULL),
('ATP','Pelambuan RW 02 Banjarmasin Barat','BJM000555','REGIONAL 4','KALSEL','BANJARMASIN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','DONE',NULL,NULL,NULL,NULL,'194',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-20',NULL,'2026-01-30',NULL,NULL),
('ATP','LOA BAKUNG RT 82, 69, 76, 22, DAN 21 SAMARINDA','SMR000399','REGIONAL 4','KALTIM','SAMARINDA',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','DONE',NULL,NULL,NULL,NULL,'744',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-09',NULL,'2026-02-02',NULL,NULL),
('ATP','KEDOKAN SAYANG RW 02 TARUB','TGL000891','REGIONAL 3','JATENG','TEGAL',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-12',NULL,NULL),
('ATP','OPEN AREA JL KEDOKAN SAYANG TARUB','TGL000969','REGIONAL 3','JATENG','TEGAL',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-12',NULL,NULL),
('ATP','MELAYU ILIR RT 01, 02, DAN 03 ASTAMBUL BANJARMASIN','BJM001347','REGIONAL 4','KALSEL','BANJARMASIN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-26',NULL,'2026-01-30',NULL,NULL),
('ATP','SUNTER AGUNG RW 06','JKT002195','REGIONAL 2','JAKARTA','JAKARTA UTARA',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'554',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-26',NULL,'2026-03-02',NULL,NULL),
('ATP','KASANG LOPAK ALAI RT 10 JAMBI','JMB001231','REGIONAL 1','JAMBI','JAMBI',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'106',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-30',NULL,'2026-03-02',NULL,NULL),
('ATP','KLOROGAN RW 03 GEGER',NULL,'REGIONAL 3','JATIM','MADIUN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','PUNCLIST','NOT STARTED',NULL,NULL,NULL,NULL,'134',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-31',NULL,'2026-02-20',NULL,NULL),
('ATP','Satreyan RW 01 Kanigoro','BLT000231','REGIONAL 3','JATIM','BLITAR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'247',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-07','2026-02-04','2026-02-16',NULL,NULL),
('RFS','Klorogan RW 02 Geger','MAD000270','REGIONAL 3','JATIM','MADIUN',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'175',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-20',NULL,NULL,NULL,NULL),
('ATP','BUKIT PINANG RT 14 SAMPAI 17 SAMARINDA','SMR000617','REGIONAL 4','KALTIM','SAMARINDA',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'849',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-20',NULL,'2026-03-20',NULL,NULL),
('RFS','SIRING AGUNG RT 01 SAMPAI 04 LUBUKLINGGAU','LLG000093','REGIONAL 1','SUMSEL','LUBUKLINGGAU',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'608',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-23',NULL,NULL,NULL,NULL),
('RFS','Ngaglik RW 01 Srengat','BLT000285','REGIONAL 3','JATIM','BLITAR',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'279',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-24',NULL,NULL,NULL,NULL),
('ATP','PILANGREJO RW 05 DAN RW 06 DEMAK','DMK001641','REGIONAL 3','JATENG','DEMAK',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'311',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-24',NULL,'2026-04-14',NULL,NULL),
('ATP','DUSUN DRONO DEMAK','DMK001642','REGIONAL 3','JATENG','DEMAK',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'180',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-24',NULL,'2026-04-13',NULL,NULL),
('RFS','KELURAHAN SELOGABUS PARENGAN TUBAN','BJN000405','REGIONAL 3','JATIM','BOJONEGORO',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'818',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-25',NULL,'2026-05-09',NULL,NULL),
('ATP','NEGLA RW 14 BREBES','BBS000939','REGIONAL 3','JATENG','BREBES',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'126',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-26',NULL,'2026-04-30',NULL,NULL),
('ATP','NEGLA RW 13 BREBES','BBS001035','REGIONAL 3','JATENG','BREBES',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'107',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-26',NULL,'2026-04-30',NULL,NULL),
('ATP','NEGLA RW 11 BREBES','BBS000940','REGIONAL 3','JATENG','BREBES',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'148',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-26',NULL,'2026-04-30',NULL,NULL),
('ATP','NEGLA RW 10 BREBES','BBS001034','REGIONAL 3','JATENG','BREBES',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'230',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-26',NULL,'2026-04-30',NULL,NULL),
('ATP','NEGLA RW 06 BREBES','BBS000937','REGIONAL 3','JATENG','BREBES',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'240',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-26',NULL,'2026-04-30',NULL,NULL),
('ATP','NEGLA RW 05 BREBES','BBS000748','REGIONAL 3','JATENG','BREBES',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'238',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-26',NULL,'2026-04-30',NULL,NULL),
('ATP','NEGLA RW 03 BREBES','BBS001033','REGIONAL 3','JATENG','BREBES',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'118',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-26',NULL,'2026-04-30',NULL,NULL),
('ATP','NEGLA RW 12 BREBES','BBS000693','REGIONAL 3','JATENG','BREBES',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'204',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-28',NULL,'2026-04-22',NULL,NULL),
('ATP','PILANGREJO RW 07 DEMAK','DMK001652','REGIONAL 3','JATENG','DEMAK',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'425',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-05',NULL,'2026-04-13',NULL,NULL),
('ATP','BANARAN RW 02 GEGER',NULL,'REGIONAL 3','JATIM','MADIUN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-20',NULL,NULL),
('ATP','Satreyan RW 06 Kanigoro','BLT000233','REGIONAL 3','JATIM','BLITAR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'296',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-02',NULL,'2026-04-25',NULL,NULL),
('ATP','RAWA MAKMUR RT 45 SAMPAI RT 47 DAN RT 49 SAMARINDA','SMR000528','REGIONAL 4','KALTIM','SAMARINDA',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'156',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-04',NULL,'2026-02-28',NULL,NULL),
('ATP','WONOKERTO RW 04 DEMAK','DMK001586','REGIONAL 3','JATENG','DEMAK',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'107',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-10',NULL,'2026-03-09',NULL,NULL),
('ATP','WONOKERTO RW 01 SAMPAI 03 DEMAK','DMK001584','REGIONAL 3','JATENG','DEMAK',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'373',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-10',NULL,'2026-03-09',NULL,NULL),
('ATP','OPEN AREA JALAN RAYA PANTURA KARANGTOWO DEMAK','DMK001583','REGIONAL 3','JATENG','DEMAK',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'295',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-10',NULL,'2026-03-10',NULL,NULL),
('ATP','KARANGTOWO RW 01 DEMAK','DMK001580','REGIONAL 3','JATENG','DEMAK',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'254',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-11',NULL,'2026-03-10',NULL,NULL),
('ATP','PERUMAHAN CITRA DAMAI 2 KEDUNGWARU TULUNGAGUNG','TLG000403','REGIONAL 3','JATIM','TULUNGAGUNG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'319',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-02',NULL,'2026-03-04',NULL,NULL),
('ATP','MENTOR RW 05 PROBOLINGGO','PBL000306','REGIONAL 3','JATIM','PROBOLINGGO',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'181',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-05',NULL,'2026-03-10',NULL,NULL),
('ATP','PERUMAHAN GRIYA BATANG HARI 8 JAMBI','JMB001178','REGIONAL 1','JAMBI','JAMBI',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'103',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-11','2026-04-01','2026-04-01',NULL,NULL),
('ATP','PERUMAHAN D''GREEN TANGKIT JAMBI','JMB001232','REGIONAL 1','JAMBI','JAMBI',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'65',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-09','2026-04-01','2026-04-01',NULL,NULL),
('ATP','PASIR PANJANG RT 05 JAMBI','JMB001199','REGIONAL 1','JAMBI','JAMBI',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'235',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-09',NULL,'2026-02-18',NULL,NULL),
('ATP','DESA SIMPANG KUBU KANDANG PEMAYUNG JAMBI','JMB001229','REGIONAL 1','JAMBI','JAMBI',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'530',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-10','2026-04-17','2026-04-17',NULL,NULL),
('ATP','KARANGJUNTI RW 05 BREBES','BBS000801','REGIONAL 3','JATENG','BREBES',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','DONE',NULL,NULL,NULL,NULL,'75',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-04',NULL,'2026-02-28',NULL,NULL),
('ATP','KARANGJUNTI RW 04 BREBES','BBS000751','REGIONAL 3','JATENG','BREBES',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'226',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-04',NULL,'2026-04-13',NULL,NULL),
('ATP','KARANGJUNTI RW 03 BREBES','BBS000945','REGIONAL 3','JATENG','BREBES',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','DONE',NULL,NULL,NULL,NULL,'128',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-04',NULL,'2026-02-28',NULL,NULL),
('ATP','KARANGJUNTI RW 02 BREBES','BBS000944','REGIONAL 3','JATENG','BREBES',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','DONE',NULL,NULL,NULL,NULL,'64',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-04',NULL,'2026-02-28',NULL,NULL),
('ATP','KARANGJUNTI RW 01 BREBES','BBS000946','REGIONAL 3','JATENG','BREBES',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'124',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-04',NULL,'2026-02-28',NULL,NULL),
('ATP','PARAKANCANGGAH RW 11 BANJARNEGARA','BNR000042','REGIONAL 3','JATENG','BANJARNEGARA',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'136',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-11',NULL,'2026-04-15',NULL,NULL),
('ATP','SUMBEREJO RW 03 GEGER',NULL,'REGIONAL 3','JATIM','MADIUN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-21',NULL,NULL),
('ATP','SIMPANG 3 SIPIN RT 33 JAMBI','JMB001244','REGIONAL 1','JAMBI','JAMBI',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'127',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-12','2026-04-01','2026-04-01',NULL,NULL),
('ATP','DESA TAMBAK ANYAR ILIR BANJARMASIN','BJM001214','REGIONAL 4','KALSEL','BANJARMASIN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'300',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-16',NULL,'2026-02-26',NULL,NULL),
('ATP','TERITIP RT 05 BALIKPAPAN','BPP000895','REGIONAL 4','KALTIM','BALIKPAPAN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'192',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-19',NULL,'2026-02-28',NULL,NULL),
('ATP','BUKIT TUNGGAL RT 05 RW 14 PALANGKARAYA','PLK000176','REGIONAL 4','KALTENG','PALANGKARAYA',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'204',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-22',NULL,'2026-02-02',NULL,NULL),
('ATP','Perumahan Kalisemi Indah Parakancanggah','BNR000048','REGIONAL 3','JATENG','BANJARNEGARA',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'221',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-24',NULL,'2026-04-15',NULL,NULL),
('ATP','KARANGTALOK RW 07 SAMPAI RW 12 PEMALANG','PML000556','REGIONAL 3','JATENG','PEMALANG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','DONE',NULL,NULL,NULL,NULL,'652',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-26',NULL,'2026-02-28',NULL,NULL),
('ATP','KARANGWAGE RW 02 PATI','PTI000379','REGIONAL 3','JATENG','PATI',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'207',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-23',NULL,'2026-03-12',NULL,NULL),
('ATP','KARANGWAGE RW 01 PATI','PTI000378','REGIONAL 3','JATENG','PATI',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'123',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-23',NULL,'2026-03-12',NULL,NULL),
('ATP','MENTENG RT 08 RW 13 PALANGKARAYA','PLK000178','REGIONAL 4','KALTENG','PALANGKARAYA',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'252',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-26',NULL,'2026-02-02',NULL,NULL),
('ATP','SATREYAN RW 02 DAN 03 BLITAR',NULL,'REGIONAL 3','JATIM','BLITAR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-25',NULL,NULL),
('ATP','DUSUN KREONGAN ATAS JEMBERLOR JEMBER','JMR000501','REGIONAL 3','JATIM','JEMBER',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'312',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-02','2026-04-30','2026-05-04',NULL,NULL),
('RFS','DUSUN PERTAMINA HAGU TEUNGOH LHOKSEUMAWE','LSM000068','REGIONAL 1','NAD','LHOKSEUMAWE',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'198',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-09',NULL,NULL,NULL,NULL),
('RFS','ROROTAN RT 01 SAMPAI 12 RW 05 JAKARTA UTARA',NULL,'REGIONAL 2','JAKARTA','JAKARTA UTARA',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'363',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-16',NULL,NULL,NULL,NULL),
('RFS','PENGGILINGAN RT 08, 09, DAN 12 RW 03 JAKARTA TIMUR','JKT006840','REGIONAL 2','JAKARTA','JAKARTA TIMUR',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'132',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-14',NULL,NULL,NULL,NULL),
('ATP','NEGLA RW 04 BREBES','BBS000749','REGIONAL 3','JATENG','BREBES',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'174',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-27',NULL,'2026-04-30',NULL,NULL),
('ATP','REJOWINANGUN RW 03 KADEMANGAN BLITAR','BLT000565','REGIONAL 3','JATENG','BLITAR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'210',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-09','2026-04-01','2026-04-02',NULL,NULL),
('ATP','REJOWINANGUN RW 04 KADEMANGAN','BLT000228','REGIONAL 3','JATENG','BLITAR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'200',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-09','2026-04-01','2026-04-02',NULL,NULL),
('ATP','PERUMAHAN MUTIARA INDAH BINTORO','JMR000306','REGIONAL 3','JATENG','JEMBER',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'201',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-03','2026-04-30','2026-05-04',NULL,NULL),
('ATP','KLANDASAN ULU RT 03 SAMPAI 22 BALIKPAPAN','BPP000916','REGIONAL 4','KALTIM','BALIKPAPAN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'831',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-02',NULL,NULL,NULL,NULL),
('ATP','PERUMAHAN TAMAN INDAH KALFANI GORONTALO','GTO000206','REGIONAL 5','GORONTALO','GORONTALO',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','PUNCLIST','NOT STARTED',NULL,NULL,NULL,NULL,'139',NULL,NULL,NULL,NULL,NULL,NULL,'2026-01-28','2026-04-23','2026-04-23',NULL,NULL),
('ATP','NEGLA RW 01 BREBES','BBS000938','REGIONAL 3','JATENG','BREBES',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'235',NULL,NULL,NULL,NULL,NULL,NULL,'2026-02-27',NULL,'2026-04-30',NULL,NULL),
('RFS','Slambur RW 02 Geger','MAD000345','REGIONAL 3','JATIM','MADIUN',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'205',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-05',NULL,NULL,NULL,NULL),
('ATP','JEBED UTARA RW 12 PEMALANG','PML000408','REGIONAL 3','JATENG','PEMALANG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'142',NULL,NULL,NULL,NULL,NULL,NULL,'2025-10-13',NULL,'2026-04-14',NULL,NULL),
('ATP','KARANGWULUH RW 02 PURWOREJO','PWR000315','REGIONAL 3','JATENG','PURWOREJO',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE','DONE','ON PROGRESS',NULL,NULL,NULL,NULL,'106',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-04','2026-04-25','2025-04-27',NULL,NULL),
('ATP','DANASARI RW 08 PEMALANG','PML000414','REGIONAL 3','JATENG','PEMALANG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'133',NULL,NULL,NULL,NULL,NULL,NULL,'2025-10-23',NULL,'2026-04-14',NULL,NULL),
('RFS','DUSUN ANGSANA DAN DUSUN PANTE OE HAGU BARAT LAUT LHOKSEUMAWE','LSM000071','REGIONAL 1','NAD','LHOKSEUMAWE',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'322',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-09',NULL,NULL,NULL,NULL),
('ATP','MANGGAR RT 06 BALIKPAPAN','BPP000896','REGIONAL 4','KALTIM','BALIKPAPAN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'243',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-26',NULL,'2026-05-12',NULL,NULL),
('ATP','OPEN AREA JALAN TERATAI GEBANG JEMBER','JMR000253','REGIONAL 3','JATIM','JEMBER',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'166',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-03','2026-04-30','2026-05-04',NULL,NULL),
('ATP','GEBANG RW 24 JEMBER','JMR000206','REGIONAL 3','JATIM','JEMBER',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'202',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-03','2026-04-30','2026-05-04',NULL,NULL),
('ATP','REJOWINANGUN RW 02 KADEMANGAN','BLT000227','REGIONAL 3','JATIM','BLITAR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'242',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-09','2026-04-27','2026-04-28',NULL,NULL),
('ATP','REJOWINANGUN RW 01 KADEMANGAN','BLT000226','REGIONAL 3','JATIM','BLITAR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'260',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-09','2026-04-27','2026-04-28',NULL,NULL),
('RFS','SUNGAI TABUK KERAMAT RT 02 BANJARMASIN','BJM001292','REGIONAL 4','KALSEL','BANJARMASIN',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'318',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-31',NULL,NULL,NULL,NULL),
('RFS','SUNGAI TABUK KERAMAT RT 01 BANJARMASIN','BJM001291','REGIONAL 4','KALSEL','BANJARMASIN',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'300',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-31',NULL,NULL,NULL,NULL),
('RFS','LAMPASEH KOTA KUTA RAJA','BNA000072','REGIONAL 1','NAD','ACEH',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'915',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-11',NULL,NULL,NULL,NULL),
('RFS','SUNGAI TABUK KERAMAT RT 03 BANJARMASIN','BJM001293','REGIONAL 4','KALSEL','BANJARMASIN',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'241',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-31',NULL,NULL,NULL,NULL),
('ATP','Lok Bahu RT 46 Sungai Kunjang','SMR000394','REGIONAL 4','KALTIM','SAMARINDA',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'252',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-05','2026-05-08','2026-05-11',NULL,NULL),
('ATP','LONING RW 03 PETARUKAN','PML000458','REGIONAL 3','JATENG','PEMALANG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'376',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-30',NULL,'2026-04-14',NULL,NULL),
('ATP','LONING RW 01 PETARUKAN','PML000425','REGIONAL 3','JATENG','PEMALANG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'702',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-27',NULL,'2026-04-14',NULL,NULL),
('ATP','KENDALDOYONG RW 01 DEMAK','DMK001563','REGIONAL 3','JATENG','DEMAK',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'313',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-12',NULL,'2026-05-12',NULL,NULL),
('ATP','KENDALDOYONG RW 03 DEMAK','DMK001651','REGIONAL 3','JATENG','DEMAK',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'146',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-10',NULL,'2026-05-12',NULL,NULL),
('ATP','KENDALDOYONG RW 04 DEMAK','DMK001520','REGIONAL 3','JATENG','DEMAK',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'154',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-12',NULL,'2026-05-12',NULL,NULL),
('ATP','KENDALDOYONG RW 06 DEMAK','DMK001541','REGIONAL 3','JATENG','DEMAK',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'235',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-14',NULL,'2026-05-12',NULL,NULL),
('RFS','LINGKUNGAN MATAJANG I MANURUNGE BONE','WTP000005','REGIONAL 5','SULSEL','BONE',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'263',NULL,NULL,NULL,NULL,NULL,NULL,'2026-03-31',NULL,NULL,NULL,NULL),
('RFS','SUNGAI BATANG RT 01 DAN 02 BANJARMASIN','BJM001351','REGIONAL 4','KALSEL','BANJARMASIN',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'277',NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-01',NULL,NULL,NULL,NULL),
('RFS','DUSUN KUPULA KEUDE ACEH LHOKSEUMAWE','LSM000020','REGIONAL 1','NAD','LHOKSEUMAWE',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'302',NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-07',NULL,NULL,NULL,NULL),
('RFS','BEGED RW 02 BOJONEGORO','BJN000503','REGIONAL 3','JATIM','BOJONEGORO',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'290',NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-07',NULL,'2026-05-09',NULL,NULL),
('ATP','Open Area Jl Kasuari Danasari','PML000295','REGIONAL 3','JATENG','PEMALANG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'226',NULL,NULL,NULL,NULL,NULL,NULL,'2025-10-25',NULL,'2026-04-14',NULL,NULL),
('ATP','Open Area Jl Rajawali Danasari','PML000298','REGIONAL 3','JATENG','PEMALANG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'315',NULL,NULL,NULL,NULL,NULL,NULL,'2025-10-23',NULL,'2026-04-14',NULL,NULL),
('ATP','JAHAB RT 01 SAMPAI 03 KUTAI KARTANEGARA','TRG000103','REGIONAL 4','KALTIM','KUTAI KARTANEGARA',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'297',NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-13','2026-05-08','2026-05-11',NULL,NULL),
('ATP','SUMBERJO RW 02 BLITAR','BLT000388','REGIONAL 3','JATIM','BLITAR',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'205',NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-13','2026-04-27','2026-04-28',NULL,NULL),
('ATP','DUSUN TULUNGREJO MADIUN','MAD000532','REGIONAL 3','JATIM','MADIUN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'195',NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-13',NULL,NULL,NULL,NULL),
('ATP','DUSUN KARANGANYAR MADIUN','MAD000531','REGIONAL 3','JATIM','MADIUN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'195',NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-13',NULL,NULL,NULL,NULL),
('ATP','BATU AMPAR RT 03 BALIKPAPAN','BPP000891','REGIONAL 4','KALTIM','BALIKPAPAN',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'216',NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-16',NULL,'2026-05-13',NULL,NULL),
('ATP','JAHAB RT 04 SAMPAI 06 KUTAI KARTANEGARA','TRG000105','REGIONAL 4','KALTIM','KUTAI KARTANEGARA',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'225',NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-14','2026-05-08','2026-05-11',NULL,NULL),
('RFS','PATRANG RW 01 JEMBER','JMR000348','REGIONAL 3','JATIM','JEMBER',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'246',NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-16',NULL,NULL,NULL,NULL),
('RFS','PONDOK MENTARI BALIKPAPAN','BPP000153','REGIONAL 4','KALTIM','BALIKPAPAN',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'373',NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-21',NULL,NULL,NULL,NULL),
('ATP','Open Area Jl. Dukuh Tanjang Pertanjungan Petarukan','PML000357','REGIONAL 3','JATENG','PEMALANG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'226',NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-23',NULL,'2026-05-12',NULL,NULL),
('RFS','OPEN AREA JL. SIKOYO PATRANG JEMBER','JMR000279','REGIONAL 3','JATIM','JEMBER',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'240',NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-30',NULL,NULL,NULL,NULL),
('RFS','GEBANG RW 10 PATRANG','JMR000157','REGIONAL 3','JATIM','JEMBER',NULL,NULL,NULL,NULL,'RFS','DONE','DONE','RELEASED','DONE',NULL,'NOT STARTED',NULL,NULL,NULL,NULL,'161',NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-16',NULL,NULL,NULL,NULL),
('ATP','JAHAB RT 14 DAN 18 KUTAI KARTANEGARA','TRG000106','REGIONAL 4','KALTIM','KUTAI KARTANEGARA',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'109',NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-27','2026-05-08','2026-05-11',NULL,NULL),
('ATP','Open Area Jl. Raya Petajungan Petarukan',NULL,'REGIONAL 3','JATENG','PEMALANG',NULL,NULL,NULL,NULL,'ATP','DONE','DONE','RELEASED','DONE',NULL,'ON PROGRESS',NULL,NULL,NULL,NULL,'614',NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-28',NULL,'2026-05-12',NULL,NULL);

DROP TEMPORARY TABLE IF EXISTS tmp_myrep_cutoff_norm_full;
CREATE TEMPORARY TABLE tmp_myrep_cutoff_norm_full AS
SELECT
  UPPER(TRIM(COALESCE(cutoff_group, ''))) AS cutoff_group,
  TRIM(COALESCE(cluster_name, '')) AS cluster_name,
  NULLIF(TRIM(COALESCE(cluster_code, '')), '') AS cluster_code,
  UPPER(TRIM(COALESCE(regional_name, ''))) AS regional_name,
  UPPER(TRIM(COALESCE(province_name, ''))) AS province_name,
  UPPER(TRIM(COALESCE(city_name, ''))) AS city_name,
  TRIM(COALESCE(team_name, '')) AS team_name,
  TRIM(COALESCE(rpm, '')) AS rpm,
  TRIM(COALESCE(sm, '')) AS sm,
  TRIM(COALESCE(spv, '')) AS spv,

  UPPER(TRIM(COALESCE(status_current, ''))) AS status_current_raw,
  UPPER(TRIM(COALESCE(status_bak, ''))) AS status_bak_raw,
  UPPER(TRIM(COALESCE(status_valsal, ''))) AS status_valsal_raw,
  UPPER(TRIM(COALESCE(status_batch_approval, ''))) AS status_batch_raw,
  UPPER(TRIM(COALESCE(status_drm, ''))) AS status_drm_raw,
  UPPER(TRIM(COALESCE(status_atp, ''))) AS status_atp_raw,
  UPPER(TRIM(COALESCE(status_checklist_document, ''))) AS status_checklist_raw,

  CAST(NULLIF(REPLACE(REPLACE(TRIM(COALESCE(hp_plan, '')), '.', ''), ',', ''), '') AS DECIMAL(18,2)) AS hp_plan,
  CAST(NULLIF(REPLACE(REPLACE(TRIM(COALESCE(homepass_bak, '')), '.', ''), ',', ''), '') AS DECIMAL(18,2)) AS homepass_bak,
  CAST(NULLIF(REPLACE(REPLACE(TRIM(COALESCE(homepass_valsal, '')), '.', ''), ',', ''), '') AS DECIMAL(18,2)) AS homepass_valsal,
  CAST(NULLIF(REPLACE(REPLACE(TRIM(COALESCE(hp_donasi, '')), '.', ''), ',', ''), '') AS DECIMAL(18,2)) AS hp_donasi,
  CAST(NULLIF(REPLACE(REPLACE(TRIM(COALESCE(homepass_drm, '')), '.', ''), ',', ''), '') AS DECIMAL(18,2)) AS homepass_drm,
  NULLIF(TRIM(COALESCE(olt_name, '')), '') AS olt_name,

  DATE(NULLIF(TRIM(COALESCE(ba_open_date, '')), '')) AS ba_open_date,
  DATE(NULLIF(TRIM(COALESCE(bak_date, '')), '')) AS bak_date,
  DATE(NULLIF(TRIM(COALESCE(valsal_date, '')), '')) AS valsal_date,
  DATE(NULLIF(TRIM(COALESCE(submission_date, '')), '')) AS submission_date,
  STR_TO_DATE(NULLIF(TRIM(COALESCE(released_at, '')), ''), '%Y-%m-%d %H:%i:%s') AS released_at,
  DATE(NULLIF(TRIM(COALESCE(drm_date, '')), '')) AS drm_date,
  DATE(NULLIF(TRIM(COALESCE(email_atp_date, '')), '')) AS email_atp_date,
  DATE(NULLIF(TRIM(COALESCE(actual_atp_date, '')), '')) AS actual_atp_date,

  CAST(NULLIF(REPLACE(REPLACE(TRIM(COALESCE(rfs_cluster_id, '')), '.', ''), ',', ''), '') AS UNSIGNED) AS rfs_cluster_id,
  NULLIF(TRIM(COALESCE(remark_general, '')), '') AS remark_general
FROM stg_myrep_cutoff_import_full
WHERE TRIM(COALESCE(cluster_name, '')) <> '';

DROP TEMPORARY TABLE IF EXISTS tmp_myrep_cutoff_final_full;
CREATE TEMPORARY TABLE tmp_myrep_cutoff_final_full AS
SELECT
  n.*,
  CASE
    WHEN n.status_current_raw <> '' THEN n.status_current_raw
    WHEN n.cutoff_group = 'ATP' THEN 'ATP'
    WHEN n.cutoff_group = 'RFS' THEN 'RFS'
    WHEN n.cutoff_group = 'IMPLEMENTASI' THEN 'DRM'
    WHEN n.cutoff_group = 'RELEASED' THEN 'RELEASED'
    WHEN n.cutoff_group = 'VALSAL' THEN 'VALSAL'
    WHEN n.cutoff_group = 'BAK' THEN 'BAK'
    ELSE 'DRAFT'
  END AS status_current_final,
  CASE
    WHEN n.status_current_raw = 'ATP' OR n.cutoff_group = 'ATP' THEN 'DONE'
    WHEN n.status_bak_raw <> '' THEN n.status_bak_raw
    ELSE 'DONE'
  END AS status_bak_final,
  CASE
    WHEN n.status_current_raw = 'ATP' OR n.cutoff_group = 'ATP' THEN 'DONE'
    WHEN n.status_valsal_raw <> '' THEN n.status_valsal_raw
    ELSE 'DONE'
  END AS status_valsal_final,
  CASE
    WHEN n.status_current_raw = 'ATP' OR n.cutoff_group = 'ATP' THEN 'RELEASED'
    WHEN n.status_batch_raw <> '' THEN n.status_batch_raw
    ELSE 'RELEASED'
  END AS status_batch_final,
  CASE
    WHEN n.status_current_raw = 'ATP' OR n.cutoff_group = 'ATP' THEN 'DONE'
    WHEN n.status_drm_raw IN ('WAITING DOC','WAITING INPUT','WAITING DOCUMENT') THEN 'DRAFT'
    WHEN n.status_drm_raw IN ('WAITING APPROVE','WAITING APPROVAL') THEN 'ON REVIEW'
    WHEN n.status_drm_raw IN ('COMPLETE','COMPLETED') THEN 'APPROVED'
    WHEN n.status_drm_raw IN ('DRAFT','SUBMITTED','ON REVIEW','APPROVED','REJECTED','DONE') THEN n.status_drm_raw
    ELSE 'DONE'
  END AS status_drm_final,
  CASE
    WHEN n.status_atp_raw IN ('DONE','PUNCLIST') THEN n.status_atp_raw
    WHEN n.status_current_raw = 'ATP' OR n.cutoff_group = 'ATP' THEN 'DONE'
    ELSE NULL
  END AS status_atp_final,
  CASE
    WHEN n.status_checklist_raw <> '' THEN n.status_checklist_raw
    WHEN n.status_current_raw = 'ATP' OR n.cutoff_group = 'ATP' THEN 'DONE'
    ELSE NULL
  END AS status_checklist_final
FROM tmp_myrep_cutoff_norm_full n;

UPDATE tb_myrep_cluster c
INNER JOIN tmp_myrep_cutoff_final_full n
  ON UPPER(TRIM(c.cluster_name)) COLLATE utf8mb4_uca1400_ai_ci = UPPER(TRIM(n.cluster_name)) COLLATE utf8mb4_uca1400_ai_ci
 AND UPPER(TRIM(c.city_name)) COLLATE utf8mb4_uca1400_ai_ci = UPPER(TRIM(n.city_name)) COLLATE utf8mb4_uca1400_ai_ci
SET
  c.rfs_cluster_id = COALESCE(n.rfs_cluster_id, c.rfs_cluster_id),
  c.cluster_code = COALESCE(n.cluster_code, c.cluster_code),
  c.regional_name = n.regional_name,
  c.province_name = n.province_name,
  c.city_name = n.city_name,
  c.team_name = n.team_name,
  c.rpm = n.rpm,
  c.sm = n.sm,
  c.spv = n.spv,
  c.hp_plan = COALESCE(n.hp_plan, c.hp_plan),
  c.status_current = n.status_current_final,
  c.remark_general = COALESCE(n.remark_general, c.remark_general),
  c.updated_at = NOW();

UPDATE tb_myrep_bak b
INNER JOIN tb_myrep_cluster c ON c.id_myrep_cluster = b.id_myrep_cluster
INNER JOIN tmp_myrep_cutoff_final_full n
  ON UPPER(TRIM(c.cluster_name)) COLLATE utf8mb4_uca1400_ai_ci = UPPER(TRIM(n.cluster_name)) COLLATE utf8mb4_uca1400_ai_ci
 AND UPPER(TRIM(c.city_name)) COLLATE utf8mb4_uca1400_ai_ci = UPPER(TRIM(n.city_name)) COLLATE utf8mb4_uca1400_ai_ci
SET
  b.ba_open_date = COALESCE(n.ba_open_date, b.ba_open_date),
  b.bak_date = COALESCE(n.bak_date, b.bak_date),
  b.homepass_bak = COALESCE(n.homepass_bak, b.homepass_bak),
  b.status_bak = n.status_bak_final,
  b.remark_bak = COALESCE(n.remark_general, b.remark_bak),
  b.updated_at = NOW();

UPDATE tb_myrep_valsal v
INNER JOIN tb_myrep_cluster c ON c.id_myrep_cluster = v.id_myrep_cluster
INNER JOIN tmp_myrep_cutoff_final_full n
  ON UPPER(TRIM(c.cluster_name)) COLLATE utf8mb4_uca1400_ai_ci = UPPER(TRIM(n.cluster_name)) COLLATE utf8mb4_uca1400_ai_ci
 AND UPPER(TRIM(c.city_name)) COLLATE utf8mb4_uca1400_ai_ci = UPPER(TRIM(n.city_name)) COLLATE utf8mb4_uca1400_ai_ci
SET
  v.valsal_date = COALESCE(n.valsal_date, v.valsal_date),
  v.homepass_valsal = COALESCE(n.homepass_valsal, v.homepass_valsal),
  v.status_valsal = n.status_valsal_final,
  v.remark_valsal = COALESCE(n.remark_general, v.remark_valsal),
  v.updated_at = NOW();

UPDATE tb_myrep_batch_approval ba
INNER JOIN tb_myrep_cluster c ON c.id_myrep_cluster = ba.id_myrep_cluster
INNER JOIN tmp_myrep_cutoff_final_full n
  ON UPPER(TRIM(c.cluster_name)) COLLATE utf8mb4_uca1400_ai_ci = UPPER(TRIM(n.cluster_name)) COLLATE utf8mb4_uca1400_ai_ci
 AND UPPER(TRIM(c.city_name)) COLLATE utf8mb4_uca1400_ai_ci = UPPER(TRIM(n.city_name)) COLLATE utf8mb4_uca1400_ai_ci
SET
  ba.submission_date = COALESCE(n.submission_date, ba.submission_date),
  ba.hp_donasi = COALESCE(n.hp_donasi, ba.hp_donasi),
  ba.released_at = COALESCE(n.released_at, ba.released_at),
  ba.staging_status = n.status_batch_final,
  ba.remark_batch_approval = COALESCE(n.remark_general, ba.remark_batch_approval),
  ba.updated_at = NOW();

UPDATE tb_myrep_drm d
INNER JOIN tb_myrep_cluster c ON c.id_myrep_cluster = d.id_myrep_cluster
INNER JOIN tmp_myrep_cutoff_final_full n
  ON UPPER(TRIM(c.cluster_name)) COLLATE utf8mb4_uca1400_ai_ci = UPPER(TRIM(n.cluster_name)) COLLATE utf8mb4_uca1400_ai_ci
 AND UPPER(TRIM(c.city_name)) COLLATE utf8mb4_uca1400_ai_ci = UPPER(TRIM(n.city_name)) COLLATE utf8mb4_uca1400_ai_ci
SET
  d.drm_date = COALESCE(n.drm_date, d.drm_date),
  d.homepass_drm = COALESCE(n.homepass_drm, d.homepass_drm),
  d.nama_olt = COALESCE(n.olt_name, d.nama_olt),
  d.status_drm = n.status_drm_final,
  d.remark_drm = COALESCE(n.remark_general, d.remark_drm),
  d.updated_at = NOW();

UPDATE tb_rfs_myrep_cluster r
INNER JOIN tmp_myrep_cutoff_final_full n ON n.rfs_cluster_id = r.id_cluster
SET
  r.email_atp_date = COALESCE(n.email_atp_date, r.email_atp_date),
  r.status_atp = COALESCE(n.status_atp_final, r.status_atp);

UPDATE tb_rfs_myrep_doc_package p
INNER JOIN tmp_myrep_cutoff_final_full n ON n.rfs_cluster_id = p.cluster_id
SET p.status_package = 'DONE'
WHERE n.status_checklist_final = 'DONE';

SELECT
  n.status_current_final AS status_current,
  COUNT(*) AS total_rows
FROM tmp_myrep_cutoff_final_full n
GROUP BY n.status_current_final
ORDER BY FIELD(n.status_current_final, 'BAK', 'VALSAL', 'RELEASED', 'DRM', 'RFS', 'ATP', 'DONE'), n.status_current_final;


