-- Struktur staging import cutoff MyRep + PO
-- Jalankan sekali untuk memastikan tabel staging permanen siap dipakai import CSV

CREATE TABLE IF NOT EXISTS stg_myrep_cutoff_import_full (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cutoff_group varchar(50) DEFAULT NULL,
  cluster_name varchar(255) DEFAULT NULL,
  cluster_code varchar(100) DEFAULT NULL,
  regional_name varchar(100) DEFAULT NULL,
  province_name varchar(100) DEFAULT NULL,
  city_name varchar(100) DEFAULT NULL,
  team_name varchar(100) DEFAULT NULL,
  rpm varchar(100) DEFAULT NULL,
  sm varchar(100) DEFAULT NULL,
  spv varchar(100) DEFAULT NULL,
  status_current varchar(50) DEFAULT NULL,
  status_bak varchar(50) DEFAULT NULL,
  status_valsal varchar(50) DEFAULT NULL,
  status_batch_approval varchar(50) DEFAULT NULL,
  status_drm varchar(50) DEFAULT NULL,
  status_atp varchar(50) DEFAULT NULL,
  status_checklist_document varchar(50) DEFAULT NULL,
  hp_plan varchar(50) DEFAULT NULL,
  homepass_bak varchar(50) DEFAULT NULL,
  homepass_valsal varchar(50) DEFAULT NULL,
  hp_donasi varchar(50) DEFAULT NULL,
  homepass_drm varchar(50) DEFAULT NULL,
  olt_name varchar(255) DEFAULT NULL,
  ba_open_date varchar(50) DEFAULT NULL,
  bak_date varchar(50) DEFAULT NULL,
  valsal_date varchar(50) DEFAULT NULL,
  submission_date varchar(50) DEFAULT NULL,
  released_at varchar(50) DEFAULT NULL,
  drm_date varchar(50) DEFAULT NULL,
  email_atp_date varchar(50) DEFAULT NULL,
  actual_atp_date varchar(50) DEFAULT NULL,
  rfs_date varchar(50) DEFAULT NULL,
  rfs_cluster_id varchar(50) DEFAULT NULL,
  po_type varchar(50) DEFAULT NULL,
  po_category varchar(50) DEFAULT NULL,
  po_number varchar(100) DEFAULT NULL,
  po_date varchar(50) DEFAULT NULL,
  po_value varchar(50) DEFAULT NULL,
  status_po varchar(50) DEFAULT NULL,
  po_version_label varchar(100) DEFAULT NULL,
  remark_po text DEFAULT NULL,
  remark_general text DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_stg_cluster_city (cluster_name, city_name),
  KEY idx_stg_cluster_code (cluster_code),
  KEY idx_stg_rfs_cluster_id (rfs_cluster_id),
  KEY idx_stg_po_number (po_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

-- Jika tabel sudah ada dari versi lama, jalankan ALTER ini (aman di MySQL 8+)
ALTER TABLE stg_myrep_cutoff_import_full
  ADD COLUMN IF NOT EXISTS rfs_date varchar(50) DEFAULT NULL AFTER actual_atp_date,
  ADD COLUMN IF NOT EXISTS po_type varchar(50) DEFAULT NULL AFTER rfs_cluster_id,
  ADD COLUMN IF NOT EXISTS po_category varchar(50) DEFAULT NULL AFTER po_type,
  ADD COLUMN IF NOT EXISTS po_number varchar(100) DEFAULT NULL AFTER po_category,
  ADD COLUMN IF NOT EXISTS po_date varchar(50) DEFAULT NULL AFTER po_number,
  ADD COLUMN IF NOT EXISTS po_value varchar(50) DEFAULT NULL AFTER po_date,
  ADD COLUMN IF NOT EXISTS status_po varchar(50) DEFAULT NULL AFTER po_value,
  ADD COLUMN IF NOT EXISTS po_version_label varchar(100) DEFAULT NULL AFTER status_po,
  ADD COLUMN IF NOT EXISTS remark_po text DEFAULT NULL AFTER po_version_label;
