CREATE TABLE IF NOT EXISTS `tb_logistik_pks` (
  `id_pks` int(11) NOT NULL AUTO_INCREMENT,
  `nomor_pks` varchar(120) NOT NULL,
  `pks_seq` int(11) NOT NULL,
  `bulan_doc` tinyint(2) NOT NULL,
  `tahun_doc` smallint(4) NOT NULL,
  `tanggal_pks` date NOT NULL,
  `pic_pks` varchar(150) NOT NULL,
  `jenis_pks` enum('MDR','MPL','PKS') NOT NULL,
  `no_telp` varchar(50) DEFAULT NULL,
  `email_pic` varchar(150) DEFAULT NULL,
  `no_ktp` varchar(50) DEFAULT NULL,
  `alamat_ktp` text,
  `grade_pic` varchar(10) DEFAULT NULL,
  `area_pic` varchar(100) DEFAULT NULL,
  `toc_pks` varchar(100) DEFAULT NULL,
  `status_pks` enum('active','non aktif') NOT NULL DEFAULT 'active',
  `workflow_status` enum('draft','waiting_approval','approved','rejected') NOT NULL DEFAULT 'draft',
  `approval_note` text,
  `signed_doc_1` varchar(255) DEFAULT NULL,
  `signed_doc_2` varchar(255) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `approved_by` int(11) DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id_pks`),
  UNIQUE KEY `uniq_nomor_pks` (`nomor_pks`),
  KEY `idx_pks_jenis` (`jenis_pks`),
  KEY `idx_pks_status` (`status_pks`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `tb_logistik_spk` (
  `id_spk` int(11) NOT NULL AUTO_INCREMENT,
  `id_pks` int(11) NOT NULL,
  `nomor_spk` varchar(120) NOT NULL,
  `spk_seq_global` int(11) NOT NULL,
  `bulan_doc` tinyint(2) NOT NULL,
  `tahun_doc` smallint(4) NOT NULL,
  `tanggal_spk` date NOT NULL,
  `bowheer` varchar(150) DEFAULT NULL,
  `project_name` varchar(200) DEFAULT NULL,
  `nilai_spk` decimal(18,2) DEFAULT 0,
  `toc_spk` varchar(100) DEFAULT NULL,
  `tanggal_amandemen_1` date DEFAULT NULL,
  `nilai_amandemen_1` decimal(18,2) DEFAULT 0,
  `tanggal_amandemen_2` date DEFAULT NULL,
  `nilai_amandemen_2` decimal(18,2) DEFAULT 0,
  `status_spk` enum('active','non aktif') NOT NULL DEFAULT 'active',
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id_spk`),
  UNIQUE KEY `uniq_nomor_spk` (`nomor_spk`),
  KEY `idx_spk_pks` (`id_pks`),
  CONSTRAINT `fk_spk_pks` FOREIGN KEY (`id_pks`) REFERENCES `tb_logistik_pks` (`id_pks`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
